[simple_commands]
qotd = "The question of the day is: What is the best scripting language?"

lurk = "Have a nice lurk! Lurkers are a power of Software and Game development streams!"
brb = "See you soon!"
unlurk = "Welcome back!"
unbrb = "Welcome back!"

youtube = "Subscribe to me on YouTube (https://www.youtube.com/@InfiniteCoder01) or/and to my second channel (https://www.youtube.com/@InfiniteCoder02)"
telegram = "Follow me on telegram: https://t.me/InfiniteCoder02"
github = "My GitHub: https://github.com/InfiniteCoder01/"
website = "My Website: https://www.infinitecoder.org"
itch = "Me on itch.io: https://infinitecoder.itch.io/"
socials = "All my contacts are here: https://www.infinitecoder.org/socials"
discord = "Join my discord server: https://discord.gg/yHYCKtX9Mt"
themes = "The themes listed here are available IF I am working in helix: https://github.com/helix-editor/helix/tree/25.01/runtime/themes"
